CREATE TABLE IF NOT EXISTS "refresh_token" (
    id UUID PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (token),
    FOREIGN KEY (id) REFERENCES "user"(id) ON DELETE CASCADE
);